### ISSUE TITLE
Watch Services

### ISSUE THREAD

**Issue by mlavacca** [Kong/blixt#18] opened 2022-11-11 11:10 UTC
## Problem Statement

Presently the `Gateway` controller simply creates `Services` of type `LoadBalancer` to get a public IP for ingress traffic, and then it "hijacks" that IP. If the `Service` is deleted however, the controller does not replace it.

## Acceptance Criteria

- [ ] the gateway controller will replace a `Service` that is deleted

**Comment by Rahul-D78** [comment] 2022-11-15 07:36
Hi @mlavacca can I work on this one I have never setup `blixt` project on kind cluster will test on kind first (the setup part) and then write the code to watch for endpoint resource, will add the IT afterwards .

**Comment by Rahul-D78** [comment] 2022-11-15 16:11
Hi @mlavacca actually not able to assign it to myself can you please assign it to me.

**Comment by Rahul-D78** [comment] 2022-11-16 15:45
Getting this error in local setup running in kind cluster can you please help
```
kubectl logs blixt-dataplane-7vvtb -n blixt-system
error: Found argument 'eth0' which wasn't expected, or isn't valid in this context

USAGE:
    blixt-dataplane [OPTIONS]

For more information try --help

```

**Comment by shaneutt** [comment] 2022-11-16 16:15
> Getting this error in local setup running in kind cluster can you please help
> 
> ```
> kubectl logs blixt-dataplane-7vvtb -n blixt-system
> error: Found argument 'eth0' which wasn't expected, or isn't valid in this context
> 
> USAGE:
>     blixt-dataplane [OPTIONS]
> 
> For more information try --help
> ```

The problem is that you're using the `latest` image. In `main` right now we're iteratively re-writing the dataplane in Rust so the `latest` image is broken in the meantime. Try changing the image to this:

```
ghcr.io/kong/blixt-dataplane@sha256:8d37ce022e289cd4235423844d858555573b6338e8f84c4ec65d3e32db132ff3
```

That's the most recent build of the Go version and should accept the argument and stop failing.

In general though the dataplane shouldn't be needed for certain kinds of controlplane work to move forward: you can just turn the dataplane off for now and focus on the controlplane logic such as updating the Service here.

**Comment by Rahul-D78** [comment] 2022-11-16 16:17
Ohhk got it thanks for the info :+1:

**Comment by Rahul-D78** [comment] 2022-11-16 16:29
Do we need to set gateway as an owner of endpoint resource

**Comment by shaneutt** [comment] 2022-11-16 16:47
> Do we need to set gateway as an owner of endpoint resource

No, and as I'm reading back over this issue it's a bit confusing. I've significantly simplified the acceptance criteria for now to make this a nice small change focused on one thing, let me know what you think.

At some point here we're going to want to start thinking about integration tests. I'm happy to do the groundwork for that so that we can test things like this, but let me know if you have any interest in trying to get the integration tests wired up to test these changes.

**Comment by Rahul-D78** [comment] 2022-11-16 16:49
So can we use envtest here setup integration testing infra

**Comment by mlavacca** [comment] 2022-12-09 10:00
Hi @Rahul-D78, are you still working on this one?

**Comment by Rahul-D78** [comment] 2022-12-09 17:22
Hey @mlavacca @shaneutt sorry for the delay I have raised a PR for Intregration test scaffolding using envtest please review thanks.

**Comment by mlavacca** [comment] 2022-12-12 13:52
@shaneutt, the gateway controller already watches the service that exposes the Gateway, it looks like this issue is already fixed. I'm not sure it makes sense to keep this one open if the issue's goal is moved to scaffolding integration tests. WDYT?

**Comment by shaneutt** [comment] 2022-12-12 14:29
Sure, let's close this and the test scaffolding can be a separate endeavor :+1:

**Closed by shaneutt** 2022-12-12 14:29 UTC
Labels: good first issue, area/control-plane
